apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp
  minReplicas: 2 # Ставим минимум 2 пода для отказоустойчивости ночью
  maxReplicas: 6 # Ставим максимум 6 подов для пиков (чисто на запас)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Масштабируем, если CPU > 70%
