apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: webapp-pdb
  namespace: default
spec:
  minAvailable: 3 # Минимум 3 пода должны быть доступны
  selector:
    matchLabels:
      app: webapp
